#!/bin/python3

# from matplotlib import colors, cm
# from matplotlib.ticker import PercentFormatter
# import matplotlib.pyplot as plt
from scipy import stats
from subprocess import Popen, PIPE
import numpy as np
import pathlib, json, glob, os
import random

## Commented out counters are zero at the 99th percentile in both fast and slow cases.
##
## TODO: figure out how to handle MSR_PEBS_FRONTEND.EVTSEL events (which have event=A6 umask=01)
## TODO: handle MEM_TRANS_RETIRED.LOAD_LATENCY_GT_* events (with event=CD umask=01)
counters = {
    "CPU_CLK_UNHALTED.REF_TSC":                                 "--event=00 --umask=03",
    # "LD_BLOCKS.STORE_FORWARD":                                  "--event=03 --umask=02",
    # "LD_BLOCKS.NO_SR":                                          "--event=03 --umask=08",
    # "LD_BLOCKS_PARTIAL.ADDRESS_ALIAS":                          "--event=07 --umask=01",
    # "DTLB_LOAD_MISSES.MISS_CAUSES_A_WALK":                      "--event=08 --umask=01",
    # "DTLB_LOAD_MISSES.WALK_COMPLETED_4K":                       "--event=08 --umask=02",
    # "DTLB_LOAD_MISSES.WALK_COMPLETED_2M_4M":                    "--event=08 --umask=04",
    # "DTLB_LOAD_MISSES.WALK_COMPLETED_1G":                       "--event=08 --umask=08",
    # "DTLB_LOAD_MISSES.WALK_COMPLETED":                          "--event=08 --umask=0E",
    # "DTLB_LOAD_MISSES.WALK_PENDING":                            "--event=08 --umask=10",
    # "DTLB_LOAD_MISSES.WALK_ACTIVE":                             "--event=08 --umask=10 --counter-mask=1",
    # "DTLB_LOAD_MISSES.STLB_HIT":                                "--event=08 --umask=20",
    "INT_MISC.RECOVERY_CYCLES":                                 "--event=0D --umask=01",
    "INT_MISC.RECOVERY_CYCLES_ANY":                             "--event=0D --umask=01 --anyt",
    "INT_MISC.CLEAR_RESTEER_CYCLES":                            "--event=0D --umask=80",
    "UOPS_ISSUED.ANY":                                          "--event=0E --umask=01",
    "UOPS_ISSUED.STALL_CYCLES":                                 "--event=0E --umask=01 --counter-mask=1 --invert",
    # "UOPS_ISSUED.VECTOR_WIDTH_MISMATCH":                        "--event=0E --umask=02",
    "UOPS_ISSUED.SLOW_LEA":                                     "--event=0E --umask=20",
    # "ARITH.DIVIDER_ACTIVE":                                     "--event=14 --umask=01",
    # "L2_RQSTS.DEMAND_DATA_RD_MISS":                             "--event=24 --umask=21",
    # "L2_RQSTS.RFO_MISS":                                        "--event=24 --umask=22",
    # "L2_RQSTS.CODE_RD_MISS":                                    "--event=24 --umask=24",
    # "L2_RQSTS.ALL_DEMAND_MISS":                                 "--event=24 --umask=27",
    # "L2_RQSTS.PF_MISS":                                         "--event=24 --umask=38",
    # "L2_RQSTS.MISS":                                            "--event=24 --umask=3F",
    "L2_RQSTS.DEMAND_DATA_RD_HIT":                              "--event=24 --umask=41",
    # "L2_RQSTS.RFO_HIT":                                         "--event=24 --umask=42",
    # "L2_RQSTS.CODE_RD_HIT":                                     "--event=24 --umask=44",
    # "L2_RQSTS.PF_HIT":                                          "--event=24 --umask=D8",
    "L2_RQSTS.ALL_DEMAND_DATA_RD":                              "--event=24 --umask=E1",
    # "L2_RQSTS.ALL_RFO":                                         "--event=24 --umask=E2",
    # "L2_RQSTS.ALL_CODE_RD":                                     "--event=24 --umask=E4",
    "L2_RQSTS.ALL_DEMAND_REFERENCES":                           "--event=24 --umask=E7",
    # "L2_RQSTS.ALL_PF":                                          "--event=24 --umask=E8",
    "L2_RQSTS.REFERENCES":                                      "--event=24 --umask=FF",
    "CORE_POWER.LVL0_TURBO_LICENSE":                            "--event=28 --umask=07",
    # "CORE_POWER.LVL1_TURBO_LICENSE":                            "--event=28 --umask=18",
    # "CORE_POWER.LVL2_TURBO_LICENSE":                            "--event=28 --umask=20",
    # "CORE_POWER.THROTTLE":                                      "--event=28 --umask=40",
    # "LONGEST_LAT_CACHE.MISS":                                   "--event=2E --umask=41",
    # "LONGEST_LAT_CACHE.REFERENCE":                              "--event=2E --umask=4F",
    "CPU_CLK_UNHALTED.THREAD_P":                                "--event=3C --umask=00",
    "CPU_CLK_UNHALTED.THREAD_P_ANY":                            "--event=3C --umask=00 --anyt",
    # "CPU_CLK_UNHALTED.RING0_TRANS":                             "--event=3C --umask=00 --counter-mask=1 --edge-detect",
    "CPU_CLK_UNHALTED.REF_XCLK":                                "--event=3C --umask=01",
    "CPU_CLK_UNHALTED.REF_XCLK_ANY":                            "--event=3C --umask=01 --anyt",
    "CPU_CLK_UNHALTED.ONE_THREAD_ACTIVE":                       "--event=3C --umask=02",
    "L1D_PEND_MISS.PENDING":                                    "--event=48 --umask=01",
    "L1D_PEND_MISS.PENDING_CYCLES":                             "--event=48 --umask=01 --counter-mask=1",
    "L1D_PEND_MISS.PENDING_CYCLES_ANY":                         "--event=48 --umask=01 --counter-mask=1 --anyt",
    # "L1D_PEND_MISS.FB_FULL":                                    "--event=48 --umask=02",
    # "DTLB_STORE_MISSES.MISS_CAUSES_A_WALK":                     "--event=49 --umask=01",
    # "DTLB_STORE_MISSES.WALK_COMPLETED_4K":                      "--event=49 --umask=02",
    # "DTLB_STORE_MISSES.WALK_COMPLETED_2M_4M":                   "--event=49 --umask=04",
    # "DTLB_STORE_MISSES.WALK_COMPLETED_1G":                      "--event=49 --umask=08",
    # "DTLB_STORE_MISSES.WALK_COMPLETED":                         "--event=49 --umask=0e",
    # "DTLB_STORE_MISSES.WALK_PENDING":                           "--event=49 --umask=10",
    # "DTLB_STORE_MISSES.WALK_ACTIVE":                            "--event=49 --umask=10 --counter-mask=1",
    # "DTLB_STORE_MISSES.STLB_HIT":                               "--event=49 --umask=20",
    # "LOAD_HIT_PRE.SW_PF":                                       "--event=4C --umask=01",
    # "EPT.WALK_PENDING":                                         "--event=4F --umask=10",
    "L1D.REPLACEMENT":                                          "--event=51 --umask=01",
    # "TX_MEM.ABORT_CONFLICT":                                    "--event=54 --umask=01",
    # "TX_MEM.ABORT_CAPACITY":                                    "--event=54 --umask=02",
    # "TX_MEM.ABORT_CAPACITY":                                    "--event=54 --umask=04",
    # "TX_MEM.ABORT_HLE_ELISION_BUFFER_NOT_EMPTY":                "--event=54 --umask=08",
    # "TX_MEM.ABORT_HLE_ELISION_BUFFER_MISMATCH":                 "--event=54 --umask=10",
    # "TX_MEM.ABORT_HLE_ELISION_BUFFER_UNSUPPORTED_ALIGNMENT":    "--event=54 --umask=20",
    # "TX_MEM.HLE_ELISION_BUFFER_FULL":                           "--event=54 --umask=40",
    # "TX_EXEC.MISC1":                                            "--event=5D --umask=01",
    # "TX_EXEC.MISC2":                                            "--event=5D --umask=02",
    # "TX_EXEC.MISC3":                                            "--event=5D --umask=04",
    # "TX_EXEC.MISC4":                                            "--event=5D --umask=08",
    # "TX_EXEC.MISC5":                                            "--event=5D --umask=10",
    "RS_EVENTS.EMPTY_CYCLES":                                   "--event=5E --umask=01",
    "RS_EVENTS.EMPTY_END":                                      "--event=5E --umask=01 --counter-mask=1 --edge-detect --invert",
    # "OFFCORE_REQUESTS_OUTSTANDING.DEMAND_DATA_RD":              "--event=60 --umask=01",
    # "OFFCORE_REQUESTS_OUTSTANDING.CYCLES_WITH_DEMAND_DATA_RD":  "--event=60 --umask=01 --counter-mask=1",
    # "OFFCORE_REQUESTS_OUTSTANDING.DEMAND_DATA_RD_GE_6":         "--event=60 --umask=01 --counter-mask=6",
    # "OFFCORE_REQUESTS_OUTSTANDING.DEMAND_CODE_RD":              "--event=60 --umask=02 --counter-mask=1",
    # "OFFCORE_REQUESTS_OUTSTANDING.DEMAND_RFO":                  "--event=60 --umask=04 --counter-mask=1",
    # "OFFCORE_REQUESTS_OUTSTANDING.ALL_DATA_RD":                 "--event=60 --umask=08",
    # "OFFCORE_REQUESTS_OUTSTANDING.CYCLES_WITH_DATA_RD":         "--event=60 --umask=08 --counter-mask=1",
    # "OFFCORE_REQUESTS_OUTSTANDING.L3_MISS_DEMAND_DATA_RD":      "--event=60 --umask=10",
    # "OFFCORE_REQUESTS_OUTSTANDING.CYCLES_WITH_L3_MISS_DEMAND_DATA_RD": "--event=60 --umask=10 --counter-mask=1",
    # "OFFCORE_REQUESTS_OUTSTANDING.L3_MISS_DEMAND_DATA_RD_GE_6": "--event=60 --umask=10 --counter-mask=6",
    "IDQ.MITE_UOPS":                                            "--event=79 --umask=04",
    "IDQ.MITE_CYCLES":                                          "--event=79 --umask=04 --counter-mask=1",
    "IDQ.DSB_UOPS":                                             "--event=79 --umask=08",
    "IDQ.DSB_CYCLES":                                           "--event=79 --umask=08 --counter-mask=1",
    "IDQ.MS_DSB_CYCLES":                                        "--event=79 --umask=10",
    "IDQ.ALL_DSB_CYCLES_4_UOPS":                                "--event=79 --umask=18 --counter-mask=4",
    "IDQ.ALL_DSB_CYCLES_ANY_UOPS":                              "--event=79 --umask=18 --counter-mask=1",
    "IDQ.MS_MITE_UOPS":                                         "--event=79 --umask=20",
    "IDQ.ALL_MITE_CYCLES_4_UOPS":                               "--event=79 --umask=24 --counter-mask=4",
    "IDQ.ALL_MITE_CYCLES_ANY_UOPS":                             "--event=79 --umask=24 --counter-mask=1",
    "IDQ.MS_CYCLES":                                            "--event=79 --umask=30 --counter-mask=1",
    "IDQ.MS_SWITCHES":                                          "--event=79 --umask=30 --counter-mask=1 --edge-detect",
    "IDQ.MS_UOPS":                                              "--event=79 --umask=30",
    # "ICACHE_16B.IFDATA_STALL":                                  "--event=80 --umask=04",
    "ICACHE_64B.IFTAG_HIT":                                     "--event=83 --umask=01",
    # "ICACHE_64B.IFTAG_MISS":                                    "--event=83 --umask=02",
    "ICACHE_64B.IFTAG_STALL":                                   "--event=83 --umask=04",
    "ITLB_MISSES.MISS_CAUSES_A_WALK":                           "--event=85 --umask=01",
    "ITLB_MISSES.WALK_COMPLETED_4K":                            "--event=85 --umask=02",
    # "ITLB_MISSES.WALK_COMPLETED_2M_4M":                         "--event=85 --umask=04",
    # "ITLB_MISSES.WALK_COMPLETED_1G":                            "--event=85 --umask=08",
    "ITLB_MISSES.WALK_COMPLETED":                               "--event=85 --umask=0E",
    "ITLB_MISSES.WALK_PENDING":                                 "--event=85 --umask=10",
    "ITLB_MISSES.WALK_ACTIVE":                                  "--event=85 --umask=10 --counter-mask=1",
    # "ITLB_MISSES.STLB_HIT":                                     "--event=85 --umask=20",
    # "ILD_STALL.LCP":                                            "--event=87 --umask=01",
    "IDQ_UOPS_NOT_DELIVERED.CORE":                              "--event=9C --umask=01",
    "IDQ_UOPS_NOT_DELIVERED.CYCLES_0_UOPS_DELIV.CORE":          "--event=9C --umask=01 --counter-mask=4",
    "IDQ_UOPS_NOT_DELIVERED.CYCLES_LE_1_UOP_DELIV.CORE":        "--event=9C --umask=01 --counter-mask=3",
    "IDQ_UOPS_NOT_DELIVERED.CYCLES_LE_2_UOP_DELIV.CORE":        "--event=9C --umask=01 --counter-mask=2",
    "IDQ_UOPS_NOT_DELIVERED.CYCLES_LE_3_UOP_DELIV.CORE":        "--event=9C --umask=01 --counter-mask=1",
    "IDQ_UOPS_NOT_DELIVERED.CYCLES_FE_WAS_OK":                  "--event=9C --umask=01 --counter-mask=1 --invert",
    "UOPS_DISPATCHED_PORT.PORT_0":                              "--event=A1 --umask=01",
    "UOPS_DISPATCHED_PORT.PORT_1":                              "--event=A1 --umask=02",
    "UOPS_DISPATCHED_PORT.PORT_2":                              "--event=A1 --umask=04",
    "UOPS_DISPATCHED_PORT.PORT_3":                              "--event=A1 --umask=08",
    "UOPS_DISPATCHED_PORT.PORT_4":                              "--event=A1 --umask=10",
    "UOPS_DISPATCHED_PORT.PORT_5":                              "--event=A1 --umask=20",
    "UOPS_DISPATCHED_PORT.PORT_6":                              "--event=A1 --umask=40",
    "UOPS_DISPATCHED_PORT.PORT_7":                              "--event=A1 --umask=80",
    "RESOURCE_STALLS.ANY":                                      "--event=A2 --umask=01",
    # "RESOURCE_STALLS.SB":                                       "--event=A2 --umask=08",
    # "CYCLE_ACTIVITY.CYCLES_L2_MISS":                            "--event=A3 --umask=01 --counter-mask=1",
    # "CYCLE_ACTIVITY.CYCLES_L3_MISS":                            "--event=A3 --umask=02 --counter-mask=2",
    "CYCLE_ACTIVITY.STALLS_TOTAL":                              "--event=A3 --umask=04 --counter-mask=4",
    # "CYCLE_ACTIVITY.STALLS_L2_MISS":                            "--event=A3 --umask=05 --counter-mask=5",
    # "CYCLE_ACTIVITY.STALLS_L3_MISS":                            "--event=A3 --umask=06 --counter-mask=6",
    "CYCLE_ACTIVITY.CYCLES_L1D_MISS":                           "--event=A3 --umask=08 --counter-mask=8",
    # "CYCLE_ACTIVITY.STALLS_L1D_MISS":                           "--event=A3 --umask=0C --counter-mask=12",
    "CYCLE_ACTIVITY.CYCLES_MEM_ANY":                            "--event=A3 --umask=10 --counter-mask=16",
    "CYCLE_ACTIVITY.STALLS_MEM_ANY":                            "--event=A3 --umask=14 --counter-mask=20",
    "EXE_ACTIVITY.EXE_BOUND_0_PORTS":                           "--event=A6 --umask=01",
    "EXE_ACTIVITY.1_PORTS_UTIL":                                "--event=A6 --umask=02",
    "EXE_ACTIVITY.2_PORTS_UTIL":                                "--event=A6 --umask=04",
    "EXE_ACTIVITY.3_PORTS_UTIL":                                "--event=A6 --umask=08",
    "EXE_ACTIVITY.4_PORTS_UTIL":                                "--event=A6 --umask=10",
    # "EXE_ACTIVITY.BOUND_ON_STORES":                             "--event=A6 --umask=40",
    # "LSD.UOPS":                                                 "--event=A8 --umask=01",
    # "LSD.CYCLES_ACTIVE":                                        "--event=A8 --umask=01 --counter-mask=1",
    # "LSD.CYCLES_4_UOPS":                                        "--event=A8 --umask=01 --counter-mask=4",
    "DSB2MITE_SWITCHES.PENALTY_CYCLES":                         "--event=AB --umask=02",
    # "ITLB.ITLB_FLUSH":                                          "--event=AE --umask=01",
    # "OFFCORE_REQUESTS.DEMAND_DATA_RD":                          "--event=B0 --umask=01",
    # "OFFCORE_REQUESTS.DEMAND_CODE_RD":                          "--event=B0 --umask=02",
    # "OFFCORE_REQUESTS.DEMAND_RFO":                              "--event=B0 --umask=04",
    # "OFFCORE_REQUESTS.ALL_DATA_RD":                             "--event=B0 --umask=08",
    # "OFFCORE_REQUESTS.L3_MISS_DEMAND_DATA_RD":                  "--event=B0 --umask=10",
    "OFFCORE_REQUESTS.ALL_REQUESTS":                            "--event=B0 --umask=80",
    "UOPS_EXECUTED.THREAD":                                     "--event=B1 --umask=01",
    "UOPS_EXECUTED.STALL_CYCLES":                               "--event=B1 --umask=01 --counter-mask=1 --invert",
    "UOPS_EXECUTED.CYCLES_GE_1_UOP_EXEC":                       "--event=B1 --umask=01 --counter-mask=1",
    "UOPS_EXECUTED.CYCLES_GE_2_UOPS_EXEC":                      "--event=B1 --umask=01 --counter-mask=2",
    "UOPS_EXECUTED.CYCLES_GE_3_UOPS_EXEC":                      "--event=B1 --umask=01 --counter-mask=3",
    "UOPS_EXECUTED.CYCLES_GE_4_UOPS_EXEC":                      "--event=B1 --umask=01 --counter-mask=4",
    "UOPS_EXECUTED.CORE":                                       "--event=B1 --umask=02",
    "UOPS_EXECUTED.CORE_CYCLES_GE_1":                           "--event=B1 --umask=02 --counter-mask=1",
    "UOPS_EXECUTED.CORE_CYCLES_GE_2":                           "--event=B1 --umask=02 --counter-mask=2",
    "UOPS_EXECUTED.CORE_CYCLES_GE_3":                           "--event=B1 --umask=02 --counter-mask=3",
    "UOPS_EXECUTED.CORE_CYCLES_GE_4":                           "--event=B1 --umask=02 --counter-mask=4",
    "UOPS_EXECUTED.CORE_CYCLES_NONE":                           "--event=B1 --umask=02 --counter-mask=1 --invert",
    # "UOPS_EXECUTED.X87":                                        "--event=B1 --umask=10",
    # "OFFCORE_REQUESTS_BUFFER.SQ_FULL":                          "--event=B2 --umask=01",
    # "TLB_FLUSH.DTLB_THREAD":                                    "--event=BD --umask=01",
    # "TLB_FLUSH.STLB_ANY":                                       "--event=BD --umask=20",
    "INST_RETIRED.ANY_P":                                       "--event=C0 --umask=00",
    "INST_RETIRED.PREC_DIST":                                   "--event=C0 --umask=01",
    # "OTHER_ASSISTS.ANY":                                        "--event=C1 --umask=3F",
    "UOPS_RETIRED.STALL_CYCLES":                                "--event=C2 --umask=01 --counter-mask=1 --invert",
    "UOPS_RETIRED.TOTAL_CYCLES":                                "--event=C2 --umask=01 --counter-mask=10 --invert",
    "UOPS_RETIRED.RETIRE_SLOTS":                                "--event=C2 --umask=02",
    "MACHINE_CLEARS.COUNT":                                     "--event=C3 --umask=01 --counter-mask=1 --edge-detect",
    "MACHINE_CLEARS.MEMORY_ORDERING":                           "--event=C3 --umask=02",
    # "MACHINE_CLEARS.SMC":                                       "--event=C3 --umask=04",
    "BR_INST_RETIRED.ALL_BRANCHES":                             "--event=C4 --umask=00",
    "BR_INST_RETIRED.CONDITIONAL":                              "--event=C4 --umask=01",
    "BR_INST_RETIRED.NEAR_CALL":                                "--event=C4 --umask=02",
    "BR_INST_RETIRED.NEAR_RETURN":                              "--event=C4 --umask=08",
    "BR_INST_RETIRED.NOT_TAKEN":                                "--event=C4 --umask=10",
    "BR_INST_RETIRED.NEAR_TAKEN":                               "--event=C4 --umask=20",
    "BR_INST_RETIRED.FAR_BRANCH":                               "--event=C4 --umask=40",
    "BR_MISP_RETIRED.ALL_BRANCHES":                             "--event=C5 --umask=00",
    # "BR_MISP_RETIRED.CONDITIONAL":                              "--event=C5 --umask=01",
    # "BR_MISP_RETIRED.NEAR_CALL":                                "--event=C5 --umask=02",
    "BR_MISP_RETIRED.NEAR_TAKEN":                               "--event=C5 --umask=20",
    # "FP_ARITH_INST_RETIRED.SCALAR_DOUBLE":                      "--event=C7 --umask=01",
    # "FP_ARITH_INST_RETIRED.SCALAR_SINGLE":                      "--event=C7 --umask=02",
    # "FP_ARITH_INST_RETIRED.128B_PACKED_DOUBLE":                 "--event=C7 --umask=04",
    # "FP_ARITH_INST_RETIRED.128B_PACKED_SINGLE":                 "--event=C7 --umask=08",
    # "FP_ARITH_INST_RETIRED.256B_PACKED_DOUBLE":                 "--event=C7 --umask=10",
    # "FP_ARITH_INST_RETIRED.256B_PACKED_SINGLE":                 "--event=C7 --umask=20",
    # "FP_ARITH_INST_RETIRED.512B_PACKED_DOUBLE":                 "--event=C7 --umask=40",
    # "FP_ARITH_INST_RETIRED.512B_PACKED_SINGLE":                 "--event=C7 --umask=80",
    # "HLE_RETIRED.START":                                        "--event=C8 --umask=01",
    # "HLE_RETIRED.COMMIT":                                       "--event=C8 --umask=02",
    # "HLE_RETIRED.ABORTED":                                      "--event=C8 --umask=04",
    # "HLE_RETIRED.ABORTED_MEM":                                  "--event=C8 --umask=08",
    # "HLE_RETIRED.ABORTED_TIMER":                                "--event=C8 --umask=10",
    # "HLE_RETIRED.ABORTED_UNFRIENDLY":                           "--event=C8 --umask=20",
    # "HLE_RETIRED.ABORTED_MEMTYPE":                              "--event=C8 --umask=40",
    # "HLE_RETIRED.ABORTED_EVENTS":                               "--event=C8 --umask=80",
    # "RTM_RETIRED.START":                                        "--event=C9 --umask=01",
    # "RTM_RETIRED.COMMIT":                                       "--event=C9 --umask=02",
    # "RTM_RETIRED.ABORTED":                                      "--event=C9 --umask=04",
    # "RTM_RETIRED.ABORTED_MEM":                                  "--event=C9 --umask=08",
    # "RTM_RETIRED.ABORTED_TIMER":                                "--event=C9 --umask=10",
    # "RTM_RETIRED.ABORTED_UNFRIENDLY":                           "--event=C9 --umask=20",
    # "RTM_RETIRED.ABORTED_MEMTYPE":                              "--event=C9 --umask=40",
    # "RTM_RETIRED.ABORTED_EVENTS":                               "--event=C9 --umask=80",
    # "FP_ASSIST.ANY":                                            "--event=CA --umask=1E --counter-mask=1",
    # "HW_INTERRUPTS.RECEIVED":                                   "--event=CB --umask=01",
    # "ROB_MISC_EVENTS.LBR_INSERTS":                              "--event=CC --umask=20",
    # "MEM_INST_RETIRED.STLB_MISS_LOADS":                         "--event=D0 --umask=11",
    # "MEM_INST_RETIRED.STLB_MISS_STORES":                        "--event=D0 --umask=12",
    # "MEM_INST_RETIRED.LOCK_LOADS":                              "--event=D0 --umask=21",
    # "MEM_INST_RETIRED.SPLIT_LOADS":                             "--event=D0 --umask=41",
    # "MEM_INST_RETIRED.SPLIT_STORES":                            "--event=D0 --umask=42",
    "MEM_INST_RETIRED.ALL_LOADS":                               "--event=D0 --umask=81",
    "MEM_INST_RETIRED.ALL_STORES":                              "--event=D0 --umask=82",
    "MEM_LOAD_RETIRED.L1_HIT":                                  "--event=D1 --umask=01",
    # "MEM_LOAD_RETIRED.L2_HIT":                                  "--event=D1 --umask=02",
    # "MEM_LOAD_RETIRED.L3_HIT":                                  "--event=D1 --umask=04",
    # "MEM_LOAD_RETIRED.L1_MISS":                                 "--event=D1 --umask=08",
    # "MEM_LOAD_RETIRED.L2_MISS":                                 "--event=D1 --umask=10",
    # "MEM_LOAD_RETIRED.L3_MISS":                                 "--event=D1 --umask=20",
    # "MEM_LOAD_RETIRED.FB_HIT":                                  "--event=D1 --umask=40",
    # "MEM_LOAD_L3_HIT_RETIRED.XSNP_MISS":                        "--event=D2 --umask=01",
    # "MEM_LOAD_L3_HIT_RETIRED.XSNP_HIT":                         "--event=D2 --umask=02",
    # "MEM_LOAD_L3_HIT_RETIRED.XSNP_HITM":                        "--event=D2 --umask=04",
    # "MEM_LOAD_L3_HIT_RETIRED.XSNP_NONE":                        "--event=D2 --umask=08",
    # "MEM_LOAD_L3_MISS_RETIRED.LOCAL_DRAM":                      "--event=D3 --umask=01",
    # "MEM_LOAD_L3_MISS_RETIRED.REMOTE_DRAM":                     "--event=D3 --umask=02",
    # "MEM_LOAD_L3_MISS_RETIRED.REMOTE_HITM":                     "--event=D3 --umask=04",
    # "MEM_LOAD_L3_MISS_RETIRED.REMOTE_FWD":                      "--event=D3 --umask=08",
    # "MEM_LOAD_MISC_RETIRED.UC":                                 "--event=D4 --umask=04",
    "BACLEARS.ANY":                                             "--event=E6 --umask=01",
    # "L2_TRANS.L2_WB":                                           "--event=F0 --umask=40",
    # "L2_LINES_IN.ALL":                                          "--event=F1 --umask=1F",
    # "L2_LINES_OUT.SILENT":                                      "--event=F2 --umask=01",
    # "L2_LINES_OUT.NON_SILENT":                                  "--event=F2 --umask=02",
    # "L2_LINES_OUT.USELESS_PREF":                                "--event=F2 --umask=04",
    # "SQ_MISC.SPLIT_LOCK":                                       "--event=F4 --umask=10",
    # "IDI_MISC.WB_UPGRADE":                                      "--event=FE --umask=02",
    # "IDI_MISC.WB_DOWNGRADE":                                    "--event=FE --umask=04",
}

print("                                           counter     normal     slow")
for name, cmd in counters.items():
    p = Popen(["target/release/seismograph", "--stdout"] + cmd.split(' '), stdout=PIPE, stderr=PIPE)

    output = p.stdout.read()

    if len(output) == 0:
        print("{} <error>".format(name.rjust(50)))
        continue

    data = json.loads(output)

    times = [[], []]
    uops = [[], []]
    values = [[], []]
    for p in data["data"]:
        if p["uops_retired"] < 600:
            i = 0
        else:
            i = 1

        times[i].append(float(p["average_cycles"])/2.4 + random.random() - 0.5)
        uops[i].append(p["uops_retired"])
        values[i].append(p["counter"])

    if int(np.percentile(values[0], 99)) == 0 and  int(np.percentile(values[1], 99)) == 0:
        print("{}".format(name.rjust(50)))
    else:
        print("{}  {:>4}/{:<4}{:>4}/{:<4}".format(name.rjust(50), int(np.percentile(values[0], 25)), int(np.percentile(values[0], 75)), int(np.percentile(values[1], 25)), int(np.percentile(values[1], 75))))
#        print("{}   {:>8} {:>8}".format(name.rjust(50), int(np.median(values[0])), int(np.median(values[1]))))
